server:
  port: 8801
  
# 项目链接前缀
project:
  url:
    prefix: /api/v1/common
  
# 开发者模式相关配置
dev:
  model:
    enable: true
    groupId: 826
    companyId: 762
    sectionId: 1167
    employeeId: 2586
    miniAppCode: '0002'
  
# 微信小程序相关配置信息
wechat:
  # 小程序编号
  mini:
    app:
      code: '0000'
  # 登录失效时间(单位s)
  login:
    timeout: 3600
    
# druid数据库连接池相关配置
druid:
  monitor:
    config:
      login:
        username: admin
        password: wx@pp@dminP@ss
      reset:
        enable: false
      allow:
        ip:
      deny:
        ip:

# mybatis相关配置
mybatis:
  # 映射文件所在路径
  mapper-locations:
  # 前面的 - 不要删除
  - classpath:mapper/**/*Mapper.xml
  
# 分页插件相关配置
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  